
build_collection(id,
                 links = NULL,
                 title,
                 assets = build_assets(tnail_object = 'png_placeholder',
                                       tnail_title = 'placeholder thumbnail title',
                                       parquet_uri = 'https://data.ecoforecst.org/forecasts/parquet/aquatics',
                                       p_title = 'Parquet STAC Items',
                                       p_description = 'Placeholder description for parquet items'),
                 extent = NULL,
                 keywords = NULL,
                 providers = NULL,
                 summaries = NULL,
                 description,
                 item_assets = NULL,
                 tables = NULL,
                 extensions = NULL,
                 publications = NULL)
